#ifndef ANIMATIONINCLUDES_H_
#define ANIMATIONINCLUDES_H_

#include "AnimationManager.h"
#include "AnimationStateMachine.h"
// Pudge Include Files
#include "PudgeIdleState.h"
#include "PudgeRunState.h"
#include "PudgeIdleToRunState.h"
#include "PudgeRunToIdleState.h"
#include "PudgeJumpState.h"
#include "PudgeIdleToJumpState.h"
#include "PudgeJumpToFallingState.h"
#include "PudgeFallingState.h"
#include "PudgeWallJumpState.h"
#include "PudgePushState.h"
#include "PudgePullState.h"
#include "PudgeIdleToPullState.h"
#include "VacuumArmIdleState.h"
#include "PudgeWallSlideState.h"
#include "PudgeBigDamageState.h"
#include "PudgeSmallDamageState.h"
#include "PudgeDeathByGooState.h"
#include "PudgeDeathByCrusherState.h"
#include "PudgeBackPeddleState.h"
// Sludge Include Files.
#include "SludgeIdleState.h"
#include "SludgePullLeverDownState.h"
#include "SludgeSpinAttackState.h"
#include "SludgeStartCrusherAttack.h"
#include "SludgeFallCrusherAttack.h"
#include "SludgeLandCrusherAttack.h"
#include "SludgeSteamAttack.h"
#include "SludgeFlyAway.h"
// Sludge Ship Include Files.
#include "SludgesShipIdleState.h"
#include "SludgesShipPullLeverDownState.h"
#include "SludgesShipSpinAttackState.h"
#include "SludgesShipStartCrusherAttack.h"
#include "SludgesShipFallCrusherAttack.h"
#include "SludgesShipLandCrusherAttack.h"
#include "SludgesShipSteamAttack.h"
#include "SludgesShipIdleDamage.h"
// Mesh Effects include files.
#include "PullEffectState.h"
#include "PushEffectState.h"
#include "ImpactEffectState.h"
#include "PullEffectIdleState.h"
#include "PushEffectIdleState.h"
#include "PullEffectPullForeverState.h"
#include "JumpEffectState.h"
#include "LandEffectState.h"
#include "BigHurtEffectState.h"
#include "LittleHurtEffectState.h"
#include "LandIdleEffectState.h"
#include "JumpIdleEffectState.h"
#include "BigHurtIdleEffectState.h"
#include "SelectionMeshSpawnState.h"
#include "SelectionMeshRotatingState.h"
#include "SpawnPipeDripState.h"
//#include "LittleHurtIdleEffectState.h"
#include "DeathCloudPudgeDeathState.h"
// Slime Include Files1
#include "SlimeMonsterIdleState.h"
#include "SlimeMonsterWalkState.h"
#include "SlimeMonsterThrowAttackState.h"
#include "SlimeMonsterSneakAttackState.h"
#include "SlimeMonsterStunState.h"
#include "SlimeMonsterDeathState.h"
#include "SlimeMonsterHideState.h"
// Lil Goo Include Files
#include "LilGooWalkState.h"
#include "LilGooAttackState.h"

#include "LilGooFlyingState.h"
// Hazards Include Files
#include "BridgeHalfRetractState.h"
#include "BridgeIdleState.h"
#include "BridgeHalfRetractIdleState.h"
#include "DoorOpenState.h"
#include "DoorIdleState.h"
#include "DoorOpenIdleState.h"
#include "ButtonIdleState.h"
#include "ButtonClosingState.h"
// Background Include Files
#include "AnimBeltState.h"
#include "AnimBoxesState.h"
#include "AnimBossState.h"
#include "AnimClawState.h"
#include "AnimFanState.h"
#include "AnimCrateClawState.h"
// Include component
#include "../ComponentManager/CComponent_Animation.h"
#include "AnimationStateMachine.h"


#endif